FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache openssl
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD sh -c "npx prisma generate && npx prisma db push && npx prisma db seed && npm run start:dev"